#!/bin/sh
set -e
package_name=sambasearch
mkdir -p "/usr/share/dpkgdivert/sambasearch"
case "$1" in
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/remoteview/smb-network.desktop")" != "" ]
then
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/remoteview/smb-network.desktop"
fi
;;
esac
exit 0
